#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sphinxcontrib-blockdiag
Version  : 1.5.5
Release  : 6
URL      : https://pypi.python.org/packages/source/s/sphinxcontrib-blockdiag/sphinxcontrib-blockdiag-1.5.5.tar.gz
Source0  : https://pypi.python.org/packages/source/s/sphinxcontrib-blockdiag/sphinxcontrib-blockdiag-1.5.5.tar.gz
Summary  : Sphinx "blockdiag" extension
Group    : Development/Tools
License  : BSD-2-Clause
Requires: sphinxcontrib-blockdiag-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=======================
sphinxcontrib-blockdiag
=======================
.. image:: https://travis-ci.org/tk0miya/sphinxcontrib-blockdiag.svg?branch=master
:target: https://travis-ci.org/tk0miya/sphinxcontrib-blockdiag

%package python
Summary: python components for the sphinxcontrib-blockdiag package.
Group: Default

%description python
python components for the sphinxcontrib-blockdiag package.


%prep
%setup -q -n sphinxcontrib-blockdiag-1.5.5

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
